name: fuel_ax
description: T.Y.MINIPROJECT

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.3
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  shared_preferences: ^2.0.8
  introduction_screen: ^2.1.0
  flip_card: ^0.6.0
  liquid_swipe: ^2.1.1
  http: ^0.13.4
  font_awesome: ^5.10.1
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.12
  rating_dialog: ^2.0.3

dev_dependencies:
  flutter_native_splash: ^1.2.4
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Fuel Ax"

flutter_native_splash:
  color: "#de9f5d"
  image: "assets/3.png"
  color_dark: "#de9f5d"
  image_dark: "assets/3.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/3.png"

  flutter_lints: ^1.0.4

flutter:
  assets:
    - assets/

  uses-material-design: true
